batch_size:
  value: 28
val_size:
  value: 0.2
transformer_size:
  value: 'large' # options are 'tiny', 'small', 'base', and 'large'
learning_rate:
  value: 0.0003
epochs:
  value: 15
weight_decay:
  value: 0.0
  #value: 0.00001
hidden_size:
  value: 32